//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpUs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casos
    {
        public int IdCaso { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdOutraEmpresa { get; set; }
        public Nullable<int> QuantidadeTotal { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string TituloCaso { get; set; }
        public string DescricaoCaso { get; set; }
        public bool Ativo { get; set; }
        public Nullable<bool> Avaliacao { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual OutrasEmpresas OutrasEmpresas { get; set; }
    }
}
