//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpUs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public Categorias()
        {
            this.Casos = new HashSet<Casos>();
        }
    
        public int IdCategoria { get; set; }
        public string NomeCategoria { get; set; }
        public int TipoCategoria { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<Casos> Casos { get; set; }
    }
}
