//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpUs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public Empresas()
        {
            this.Casos = new HashSet<Casos>();
            this.Login = new HashSet<Login>();
            this.PessoasSolicitantes = new HashSet<PessoasSolicitantes>();
        }
    
        public int IdEmpresa { get; set; }
        public string NomeEmpresa { get; set; }
        public string EmailEmpresa { get; set; }
        public string Cnpj { get; set; }
        public string CEP { get; set; }
        public int TelefoneEmpresa { get; set; }
        public string UfEmpresa { get; set; }
        public string CidadeEmpresa { get; set; }
        public bool ativo { get; set; }
        public Nullable<System.DateTime> DataDisativacao { get; set; }
    
        public virtual ICollection<Casos> Casos { get; set; }
        public virtual ICollection<Login> Login { get; set; }
        public virtual ICollection<PessoasSolicitantes> PessoasSolicitantes { get; set; }
    }
}
