//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpUs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutrasEmpresas
    {
        public OutrasEmpresas()
        {
            this.Casos = new HashSet<Casos>();
            this.Login = new HashSet<Login>();
            this.PessoasSolicitantes = new HashSet<PessoasSolicitantes>();
        }
    
        public int IdOutraEmpresa { get; set; }
        public string OutraOutrasEmpresas { get; set; }
        public string EmailOutrasEmpresas { get; set; }
        public string CEPOutrasEmpresas { get; set; }
        public int TelefoneOutrasEmpresas { get; set; }
        public string UfOutrasEmpresas { get; set; }
        public string CidadeOutrasEmpresas { get; set; }
        public bool ativo { get; set; }
        public Nullable<System.DateTime> DataDisativacao { get; set; }
    
        public virtual ICollection<Casos> Casos { get; set; }
        public virtual ICollection<Login> Login { get; set; }
        public virtual ICollection<PessoasSolicitantes> PessoasSolicitantes { get; set; }
    }
}
